### PR TITLE
Fix: Include config warnings and expose certain methods.

### LINKED ISSUE #44: Warn when session count is 0 in config.
I had really hard time trying to figure out why stcp doesn't work at all. Actually the problem was in the setup node's config, there was mistype in `sessions_count` field, so actual sessions count was 0 in the dmsg client config. But it wasn't obvious at all looking at the logs. This partciular thing should be at least logged with the warning if sessions count is 0, cause it's really hard to diagnose the cause of the problem

_Originally posted by @Darkren in https://github.com/SkycoinProject/skywire-mainnet/issues/123#issuecomment-577752770_

### PR DESCRIPTION
**Pull request by evanlinjin**
Fixes #44 

 Changes:	
- Added `Config.PrintWarnings()` method to print warnings to log.
- Exposed `Client` methods: `Session()`, `AllSessions()` and `EnsureAndObtainSessions()`.

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -197,27 +209,24 @@ func (ce *Client) DialStream(ctx context.Context, addr Addr) (*Stream, error) {
...
+// AllSessions obtains all established sessions.
+func (ce *Client) AllSessions() []ClientSession {
+	return ce.allClientSessions(ce.porter)
 }
 
-func (ce *Client) obtainSession(ctx context.Context, srvPK cipher.PubKey) (ClientSession, error) {
+// EnsureSession attempts to obtain a session.
+// If the session does not exist, we will attempt to establish one.
+// It returns an error if the session does not exist AND cannot be established.
+func (ce *Client) EnsureSession(ctx context.Context, srvPK cipher.PubKey) (ClientSession, error) {
```
Comment (nkryuchkov) [inline client.go]: I would give different names to `EnsureSession` and `ensureSession` because it's not clear from their name what is their difference
